/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Join the Discord!": "加入 Discord!",
    "Fix export button and save": "修复导出按钮和保存",
    "ENABLED": "启用",
    "Export to file": "导出为文件",
    "Import clipboard": "从剪贴板导入",
    "Import file": "从文件导入",
    "DISABLED": "禁用",
    "Experience": "经验值",
    "Head": "头部",
    "Idle": "空闲",
    "Import Save": "导入存档",
    "Iron": "铁",
    "Level — · XP —": "等级 — · 经验值 —",
    "Lv": "等级",
    "Logs": "日志",
    "Lvl": "等级",
    "Mana": "法力",
    "Mana:": "法力:",
    "Metal": "金属",
    "Mining": "采矿",
    "Axe": "斧子",
    "Autosave": "自动保存",
    "Attack": "攻击",
    "Atk": "攻击",
    "Apply": "应用",
    "Amulet": "护符",
    "Kills:": "击杀:",
    "Legs": "腿部",
    "Max Hit:": "最大命中:",
    "level speeds crafting.": "等级加速制作。",
    "HP — · Atk — · Def — · Max —": "生命值 — · 攻击 — · 防御 — · 最大 —",
    "Food": "食物",
    "Export Save": "导出存档",
    "Fish": "钓鱼",
    "Fishing": "钓鱼",
    "Essences": "精华",
    "Enchanting": "强化",
    "Eat": "吃",
    "Eat": "吃",
    "Def": "防御",
    "Defense": "防御",
    "Crafting": "制作",
    "Craft": "制作",
    "Copper": "铜",
    "Cooking": "烹饪",
    "Combat Log": "战斗日志",
    "and": "和",
    "⚒️ Smithing": "⚒️ 锻造",
    "⚔️ Combat": "⚔️ 战斗",
    "⛏️ Mining": "⛏️ 采矿",
    "⛰️ Mountains": "⛰️ 山脉",
    "🌋 Volcano": "🌋 火山",
    "🌲 Chop Trees": "🌲 砍树",
    "🌲 Forests": "🌲 森林",
    "🌿 Swamp": "🌿 沼泽",
    "🍳 Cooking": "🍳 烹饪",
    "🎒 Inventory": "🎒 库存",
    "🎣 Fishing": "🎣 钓鱼",
    "🏜️ Wastes": "🏜️ 废物",
    "👑 Royal Service": "👑 皇家服务",
    "📜 Log": "📜 日志",
    "🔥 Smelting": "🔥 锻造",
    "🧙 Character": "🧙 角色",
    "🧭 Skills": "🧭 技能",
    "🧰 Equipment": "🧰 装备",
    "🪄 Enchanting": "🪄 强化",
    "🪚 Crafting": "🪚 制作",
    "🪦 Crypts": "🪦 地穴",
    "🛠️ Upgrade Gear": "🛠️ 升级装备",
    "🛡️ Forge Gear & Materials": "🛡️ 锻造装备 & 材料",
    "Book": "书",
    "Books": "书",
    "Body": "身体",
    "Bronze": "青铜",
    "Chop": "砍树",
    "Drop raw food here": "拖动生的食物到这里",
    "Drag a": "拖动一个",
    "Rune": "符文",
    "Sell": "出售",
    "Shared": "均衡",
    "Smelt 1": "锻造1个",
    "Smelt All": "锻造全部",
    "Smithing": "锻造",
    "Spend": "花费",
    "Start Fight": "开始战斗",
    "Steel": "钢",
    "Str": "力量",
    "Strength": "力量",
    "Sturdy Pole": "坚固的杆子",
    "Swamp Elemental": "沼泽元素",
    "Swamp Spider": "沼泽蜘蛛",
    "Tip: Click a monster to select and Fight.": "提示：点击一个怪物来选择和战斗。",
    "(higher Smithing skews higher).": "（越高的锻造越倾斜）。",
    ") can be upgraded up to 100%.": ") 可升级至100%。",
    "Fishing Pole": "钓竿",
    "Forestry": "林业",
    "Glass Vial": "玻璃小瓶",
    "Gold": "金币",
    "golden zone": "黄金地带",
    "Gutter Rat": "沟鼠",
    "Reset": "重置",
    "Royal Service": "皇家服务",
    "Tome": "卷轴",
    "Tomes": "卷轴",
    "Total": "总计",
    "Tree": "树",
    "Wood Handle": "木柄",
    "You": "你",
    "using": "用于",
    "Toxic Frog": "毒蛙",
    ". Higher Enchanting level unlocks more recipes.": "。更高的附魔等级可以解锁更多的配方。",
    ". Too short = raw. Too long = burnt.": "。时间太短 = 生的。时间太长 = 烧焦。",
    "Tip: Items with a quality (e.g.,": "提示：有质量的物品 (例如：",
    "— Favor": "— 徽章",
    "Pond Shallows": "池塘浅滩",
    "Spot": "地点",
    "Rock": "岩石",
    "Style": "风格",
    "Drops": "掉落",
    "Flee": "逃跑",
    "Oak ": "橡树",
    "Pine ": "松树",
    "Bog Mite": "沼泽螨",
    "Cape": "披风",
    "Bramble Sprite": "荆棘精灵",
    "Nothing upgradable": "暂无可升级",
    "No active contract. Click “Request Contract”.": "没有有效合同。点击“请求合同”。",
    "Pages": "纸",
    "raw food": "生冷食物",
    "Reinforced Vial": "加强小瓶",
    "Request Contract": "请求合同",
    "Turn": "回合",
    "to improve quality by": "提高质量通过",
    "Anglers Pride": "琵琶鱼的骄傲",
    "Blacksteel": "黑钢",
    "Bar": "锭",
    "Cut": "切割",
    "Advanced Forest Tome": "高级森林卷轴",
    "Advanced Rock Tome": "高级岩石卷轴",
    "Advanced Sea Tome": "高级海洋卷轴",
    "Enchant Advanced Forest Tome": "附魔高级森林卷轴",
    "Enchant Advanced Rock Tome": "附魔高级岩石卷轴",
    "Enchant Advanced Sea Tome": "附魔高级海洋卷轴",
    "Enchant Novice Forest Tome": "附魔新手森林卷轴",
    "Enchant Novice Rock Tome": "附魔新手岩石卷轴",
    "Enchant Novice Sea Tome": "附魔新手海洋卷轴",
    "Enchant Apprentice Sea Tome": "附魔学徒海洋卷轴",
    "Enchant Apprentice Rock Tome": "附魔学徒岩石卷轴",
    "Enchant Apprentice Forest Tome": "附魔学徒森林卷轴",
    "Apprentice Sea Tome": "学徒海洋卷轴",
    "Apprentice Rock Tome": "学徒岩石卷轴",
    "Apprentice Forest Tome": "学徒森林卷轴",
    "hammer": "锤子",
    "Incremental": "增量",
    "Mine": "采矿",
    "Ore": "矿石",
    "Oak Logs": "橡木",
    "Forest Essence": "森林精华",
    "Rock Essence": "岩石精华",
    "Sand Vein ": "砂脉",
    "from your inventory onto the fire and hold it.\n            Release when the bar is in the": "从你的库存，放在火上并保持.\n            释放时机是当你进度条在",
    "Notice: Game is in very early development.": "注意：游戏还处于早期开发阶段。",
    "Empty": "空",
    "Saved ✓": "已保存 ✓",
    "Craft items from gathered materials. Higher": "用收集到的材料制作物品。更高的",
    "Abandon Contract": "放弃合同",
    "into": "到",
    "Birch Planks": "桦木板",
    "Bog Hydra": "沼泽九头蛇",
    "Cedar Planks": "雪松木板",
    "Elderwood Planks": "接骨木木板",
    "Maple Planks": "枫木木板",
    "Pine Planks": "松木木板",
    "Willow Planks": "柳木木板",
    "Yew Planks": "紫杉木木板",
    "Runewood Planks": "符文木木板",
    "Oak Planks": "橡木木板",
    "Marsh Colossus": "沼泽巨人",
    "Auto-fishing…": "自动钓鱼中...",
    "Auto-chopping…": "自动砍树中...",
    "River Bend": "河湾",
    "Miss": "未命中",
    " misses you.": "没有命中你。",
    "Unknown": "未知",
    "Bone Rat": "骨鼠",
    "Charred Bat": "烧焦蝙蝠",
    "Cliff Rat": "悬崖老鼠",
    "Crypt Bat": "地穴蝙蝠",
    "Crypt Lich": "地穴巫妖",
    "Death Priest": "死亡牧师",
    "Dune Titan": "沙丘巨人",
    "Dust Rat": "尘鼠",
    "Fire Mite": "火螨",
    "Flame Ogre": "火焰食人魔",
    "Frost Drake": "霜龙",
    "Glass Scorpion": "玻璃蝎子",
    "Grave Ghoul": "墓穴食尸鬼",
    "Ice Wolf": "冰狼",
    "Inferno Colossus": "地狱巨人",
    "Lava Hound": "熔岩猎犬",
    "Magma Goblin": "岩浆哥布林",
    "Mountain Goat": "山羊",
    "Peak Giant": "巅峰巨人",
    "Pyre Drake": "火葬龙兽",
    "Rock Troll": "岩石巨魔",
    "Sand Beast": "沙兽",
    "Scavenger Dog": "清道夫犬",
    "Shadow Wraith": "暗影幽灵",
    "Storm Colossus": "风暴巨人",
    "Thorn Lizard": "棘蜥",
    "Tomb Knight": "坟墓骑士",
    "Waste Vulture": "废物秃鹫",
    "Ready: Raw Halibut — hold to cook": "就绪：生大比目鱼 — 按下进行烹饪",
    "Ready: Raw Salmon — hold to cook": "就绪：生鲑鱼 — 按下进行烹饪",
    "Ready: Raw Trout — hold to cook": "就绪：生鳟鱼 — 按下进行烹饪",
    "Ready: Raw Shrimp — hold to cook": "就绪：生虾 — 按下进行烹饪",
    "Removed too early — still raw": "过早移除 - 仍是生的",
    "Burnt Raw Salmon": "烧焦的生鲑鱼",
    "Burnt Raw Eel": "烧焦的生鳗鱼",
    "Burnt Raw Angler": "烧焦的生琵琶鱼",
    "Burnt Raw Trout": "烧焦的生鳟鱼",
    "Burnt Raw Shrimp": "烧焦的生虾",
    "Pine Logs": "松木",
    "Raw Shrimp": "生虾",
    "Sea Essence": "海洋精华",
    "Shrimp": "虾",
    "You fled from Bramble Sprite.": "你逃离了荆棘精灵。",
    "Version: 1.3.5 Notice: Refresh your page if you encounter a bug.": "版本:1.3.5 注意: 如果你遇到一个错误，请刷新页面。",
    "Craft Oak Planks": "制作橡木板",
    "Craft Pages": "制作纸",
    "Craft Wood Handle": "制作木柄",
    "Plate": "板甲",
    "Raw Trout": "生鳟鱼",
    "Marsh": "沼泽",
    "Wire Coil": "线圈",
    "You were defeated.": "你被击败了。",
    "Oak Plank": "橡木板",
    "Yew Plank": "紫杉木板",
    "Turn In Contract": "移交合同",
    "Turn In": "提交",
    "Reward:": "奖励:",
    "Pick": "镐",
    "Deliver:": "交付:",
    "The Royal Craftsman has requested the following in service to the kingdom:": "皇家工匠要求为皇家服务提供如下物品：",
    "Delivered:": "已交付:",
    "Craft Fishing Pole": "制作鱼竿",
    "Tin Seam ": "锡矿层",
    "Deposit ": "矿床",
    "Raw Eel": "生鳗鱼",
    "Trout": "鳟鱼",
    "Silica Sand": "硅砂",
    "Birch ": "桦树",
    "Cedar ": "雪松",
    "Willow ": "柳树",
    "Craft Pine Planks": "制作松木板",
    "Craft Glass Vial": "制作玻璃小瓶",
    "Craft Reinforced Vial": "制作加强小瓶",
    "Coal Bed ": "煤床",
    "River": "河流",
    "Open Ocean": "公海",
    "Coast": "海岸",
    "Pine Plank": "松木板",
    "← Back": "← 返回",
    "Construction": "建筑",
    "Camp 🔒": "营地 🔒",
    "Camp": "营地",
    "Build": "建造",
    "Auto-cook —": "自动烹饪 —",
    "Coal": "煤",
    "Salmon": "鲑鱼",
    "Raw Salmon": "生鲑鱼",
    "Halibut": "大比目鱼",
    "Raw Halibut": "生大比目鱼",
    "Raw Manta Ray": "生蝠鲼",
    "Manta Ray": "蝠鲼",
    "Eel": "鳗鱼",
    "Glass Glob": "玻璃球",
    "Tin Ore": "锡矿石",
    " Wire Coil": "线圈",
    "Royal Contract Complete!": "皇家合同已完成！",
    "The Royal Quartermaster has requested the following food supplies in service to the kingdom:": "皇家军需官要求为王国提供以下食物：",
    "The Royal Quartermaster has requested the following building supplies:": "皇家军需官要求提供以下建筑用品：",
    "Slay:": "击杀:",
    "The Royal Warden calls upon you to defend the kingdom:": "皇家监狱长呼吁你保卫王国:",
    "Accuracy Potion": "精准药水",
    "Alchemy": "炼金",
    "Autobattle": "自动战斗",
    "Brew": "酿造",
    "Craft potions from gathered reagents. Higher Alchemy level speeds brewing.": "从收集的试剂中制作药剂。更高炼金术等级可以加速酿造。",
    "Favor Bonuses": "徽章加成",
    "Mana Potion": "法力药水",
    "Arcane Mana Potion": "奥术法力药水",
    "Arcane Accuracy Potion": "奥术精准药水",
    "Small Mana Potion": "小型法力药水",
    "Birch Logs": "桦木原木",
    "Available now": "当前可用",
    "Elderwood ": "接骨木",
    "Maple ": "枫木",
    "Maple Logs": "枫木原木",
    "Runewood ": "符文木",
    "Unlocked": "已解锁",
    "Yew ": "紫杉木",
    "Willow Logs": "柳木原木",
    "Max tier.": "最大层级。",
    "No buildings available.": "没有可用的建筑物。",
    "Nightiron Vein ": "夜铁矿脉",
    "Defense Potion": "防御药水",
    "Cedar Logs": "雪松原木",
    "Advanced Accuracy": "高级精准",
    "Batch:": "批量：",
    "Advanced Defense": "高级防御",
    "Inventory Sort": "库存排序",
    "Sort": "排序",
    "Shadowline Rod": "影线杆",
    "The Royal Armorer has issued a contract to arm the kingdom's troops:": "皇家军械师签署了一份为王国军队提供武器的合同",
    "Yew Logs": "紫杉原木",
    "Halibut": "",
    "Craft Cedar Planks": "制作雪松木板",
    "Craft Willow Planks": "制作柳木木板",
    "Craft Birch Planks": "制作桦木木板",
    "Upgrade": "升级",
    "A cheerful baby chick peeking out of his cracked egg, glowing with warmth and curiosity—your first loyal pet companion": "一只欢快的小鸡从破蛋里探出头来，散发着温暖和好奇的光芒——你的第一个忠实的宠物伴侣",
    "Asterium Cluster ": "星宿簇",
    "cheeken": "小鸡",
    "Construct": "建筑",
    "Pets": "宠物",
    "Pets 🔒": "宠物 🔒",
    "Service": "服务",
    "Starsteel": "星钢",
    "Elderwood Logs": "接骨木原木",
    "Auto-cooking Halibut —": "自动烹饪 大比目鱼 —",
    "A cheerful baby chick peeking out of his cracked egg, glowing with warmth and curiosity—your first loyal pet companion.": "一只欢快的小鸡从破蛋里探出头来，散发着温暖和好奇的光芒——你的第一个忠实的宠物伴侣。",
    "Abyssal Trench": "深渊海沟",
    "Cheeken": "小鸡",
    "Fight": "战斗",
    "Equipped": "已装备",
    "Max": "最大",
    "Royal Service Dog": "皇家服务犬",
    "The Royal Steward has requested the following food supplies:": "皇家管家要求以下食品供应:",
    "Angler": "琵琶鱼",
    "Asterium Ore": "星宿矿石",
    "Birch Bark Resin": "桦树皮树脂",
    "Bramble Heart": "荆棘之心",
    "Briar Oil": "石楠油",
    "Leather": "皮革",
    "Nails": "钉子",
    "Nightiron Ore": "夜铁矿石",
    "Quicksilver(e)": "水银(e)",
    "Raw Angler": "生琵琶鱼",
    "Silk Coil": "丝圈",
    "The Royal Craftsman has requested the following goods:": "皇家工匠要求以下货物：",
    "Bluewater Run": "蓝水湾",
    "Bat Teeth": "蝙蝠牙齿",
    "Cedar Bark Resin": "雪松皮树脂",
    "Nylon Coil": "尼龙线圈",
    "Raw Bluefin Tuna": "生蓝鳍金枪鱼",
    "Pet Fight": "宠物战斗",
    "Monster": "怪物",
    "Your pet was defeated.": "你的宠物被击败了。",
    "Equip": "装备",
    "Asterium Cluster": "星宿簇",
    "Birch": "桦树",
    "Cedar": "雪松",
    "Coal Bed": "煤床",
    "Deposit": "矿床",
    "Maple": "枫树",
    "Nightiron Vein": "夜铁矿脉",
    "Oak": "橡树",
    "Pine": "松树",
    "Stop": "停止",
    "Sand Vein": "砂脉",
    "Variant": "变体",
    "Tin Seam": "锡缝",
    "Willow": "柳树",
    "Crypt Cord": "地穴绳",
    "Ghoul Eye": "食尸鬼的眼睛",
    "Quicksilver": "水银",
    "Enchant Emerald Ring": "附魔翡翠戒指",
    "Enchant Ruby Ring": "附魔红宝石戒指",
    "Enchant Starstone Ring": "附魔星彩石戒指",
    "Enchant Diamond Ring": "附魔钻石戒指",
    "Enchant Sapphire Ring": "附魔蓝宝石戒指",
    "Diamond Ring": "钻石戒指",
    "Emerald Ring": "翡翠戒指",
    "Sapphire Ring": "蓝宝石戒指",
    "Starstone Ring": "星彩石戒指",
    "Ruby Ring": "红宝石戒指",
    "Birch Plank": "桦木板",
    "Cedar Plank": "雪松木板",
    "Novice Forest Tome": "新手森林卷轴",
    "Novice Rock Tome": "新手岩石卷轴",
    "Novice Sea Tome": "新手海洋卷轴",
    "Runs for: 25s (scales with Enchanting)": "运行时间: 25s（附魔缩放）",
    "A loyal royal service hound who earned his crown assisting the court—steadfast, brave, and always at your side after countless duties for the realm.": "一只忠诚的皇家勤务犬，通过协助宫廷赢得了王冠——坚定，勇敢，在为王国尽了无数的职责后，永远在你身边。",
    "Sterling": "斯特林",
    "Stopped auto-chopping…": "停止自动伐木...",
    "Switched to Maple.": "已切换到枫树。",
    "Switched to Yew.": "已切换到紫杉树。",
    "Yew": "紫杉",
    "Bluefin Tuna": "蓝鳍金枪鱼",
    "Started auto-mining… at Iron Deposit.": "开始自动采矿...铁矿脉。",
    "Started auto-chopping… at Yew.": "开始自动伐木...紫杉树。",
    "Sandreaver": "挖沙船",
    "No pets yet.": "还没有宠物。",
    "No items yet. Gather or fight to earn loot.": "还没有东西。收集或战斗赚取战利品。",
    "Stopped fish to smelt.": "停止钓鱼改为锻造",
    "Started auto-fishing… at Bluewater Run.": "在蓝水湾开始自动钓鱼。",
    "Brew Small Mana Potion": "酿造小法力药水",
    "Brew Defense Potion": "酿造防御药水",
    "❤ Buy Dev Coffee": "❤ 请开发者喝杯咖啡",
    "🏕️ Construct": "🏕️ 建筑",
    "👹 Bosses": "👹 Boss",
    "🧪 Alchemy": "🧪 炼金",
    "🔥 Destruction": "🔥 破坏",
    "🪓 Forestry": "🪓 林业",
    "Level": "等级",
    "Tips": "提示",
    "XP": "经验值",
    "Water Bolt Spell": "水箭法术",
    "Thornstorm Spell": "荆棘风暴法术",
    "Rock Barrage Spell": "岩坝法术",
    "Razorleaf Spell": "剃刀法术",
    "Fireball Spell": "火球法术",
    "Explosion Spell": "爆炸法术",
    "Ember Spell": "余烬法术",
    "Splash Spell": "溅射法术",
    "Inferno Spell": "地狱法术",
    "Stone Throw Spell": "投石法术",
    "Leaf Dart Spell": "叶镖法术",
    "Tidal Surge Spell": "潮涌法术",
    "Spells & Potions": "法术 & 药水",
    "You and Sterling": "你和斯特林",
    "General": "常规",
    "Silver Sapphire Amulet": "银蓝宝石护符",
    "Silver Ruby Amulet": "银红宝石护符",
    "Gold Diamond Amulet": "黄金钻石护符",
    "Gold Starstone Amulet": "黄金星石护符",
    "Gold Emerald Amulet": "黄金翡翠护符",
    "Bosses": "Boss",
    "Destruction": "破坏",
    "Draconyx": "龙爪龙",
    "Retreat": "撤退",
    "Swamp Guardian": "沼泽守护者",
    "Mythril Current": "神话当前",
    "Runebound Rod": "符文结合棒",
    "Vein": "矿脉",
    "A good place to start is by mining some ores, smelting them into bars, and forging them into armor": "一个好的开始是开采一些矿石，将它们熔炼成金属条，然后将它们锻造成盔甲",
    "All fishing locations have a chance to drop sea essence which can be used in enchanting": "所有捕鱼地点都有机会掉落海精，可以用来附魔",
    "All ores have a chance to drop rock essence which can be used in enchanting": "所有矿石都有一定几率掉落可用于附魔的岩石精华",
    "All trees have a chance to drop Forest Essence which is useful in enchanting": "所有的树都有机会掉落森林精华，这对附魔很有用",
    "Attack increases accuracy and has a small contribution to max hit": "攻击增加精度，对最大命中有很小的贡献",
    "Coils and chords are dropped by monsters. Bog mite drops the wire coil": "怪物会丢下线圈和琴弦。沼泽怪把线圈掉在地上",
    "Craft some vials and gather ingredients to make potions to help you in battle": "制作一些瓶子和收集成分，使药水，以帮助你在战斗中",
    "Create Spells to be used in battle. Gain xp when creating spells and when using them.": "创造在战斗中使用的法术。创造法术和使用法术时获得经验值。",
    "Defense reduces the damage received by monsters and increases your maximum hp": "防御降低怪物的伤害，提高你的最大生命值",
    "Drag the buildings to where you want them to customize your camp": "拖动建筑物到你想要的地方，以自定义你的营地",
    "Each enchanting level adds to your maximum mana": "每一层附魔都会增加你的最大法力值",
    "Each level increases the speed at which you can cut down a tree": "每升一级，你砍树的速度就会加快",
    "Elderwood Tidecaller": "接骨木潮汐者",
    "Enchant Arcane Phial": "附魔奥术小瓶",
    "Enchant Expert Forest Tome": "附魔专家森林卷轴",
    "Enchant Expert Rock Tome": "附魔专家岩石卷轴",
    "Enchant Expert Sea Tome": "附魔专家海洋卷轴",
    "Enchant Phial": "附魔小瓶",
    "Enchanted Mana Potion": "魔法药水",
    "Enchanting consumes mana as well as ingredients": "附魔消耗魔法和原料",
    "Equip a ring and enchant to gain useful effects": "装备一个戒指并附魔以获得有用的效果",
    "Equip a tool and drag enchanted quicksilver to increase the tool's speed": "装备一个工具，拖拽附魔水银来提高工具的速度",
    "Equipping a pickaxe greatly increases the speed": "装备鹤嘴锄大大提高了速度",
    "Equipping an axe further increases this speed": "装备斧头会进一步提高这个速度",
    "Export your save to play cross browser or device. Clearing your cookies will delete your progress as tthe game state is stored in local storage": "导出您的保存播放跨浏览器或设备。清除你的cookies将删除你的进度，因为游戏状态被存储在本地存储中",
    "Fishing speed increases with each level over the requirement for that fishing location": "捕鱼速度随着等级的提高而增加，超过了对捕鱼地点的要求",
    "Gather supplies or kill monsters for the royal court to earn Royal Favor": "为皇室收集补给或杀死怪物以获得皇室的青睐",
    "Gathering resources has a 30 second AFK timer. This can be increased by constructing buildings in your camp": "收集资源有一个30秒的AFK计时器。这可以通过在你的营地建造建筑来增加",
    "Gear has a quality between 0-100%. Use upgrade bars to increase the quality and increase the stats": "齿轮的质量在0-100%之间。使用升级条来提高质量和属性",
    "Hover over monsters to see drops that you've unlocked": "悬停在怪物上看你已经解锁的掉落物",
    "Increasing your level increases the size of the golden zone and the speed of cooking": "增加你的等级会增加黄金区域的大小和烹饪的速度",
    "Mining has a chance to drop gems with the rarity and likelihood increasing in higher tier ores": "采矿有机会掉落宝石，随着稀缺性和可能性在更高层次的矿石中增加",
    "Mining speed increases with each level above the requirement of that specific ore": "采矿速度随着高于特定矿石要求的每一级而增加",
    "Optionally you can click and hold the fire until it reaches the golden zone": "你可以选择点击并按住火，直到它到达黄金区域",
    "Refresh your page if something doesnt look right. I push multiple updates per day and you may need to refresh to get the latest version": "如果有什么不对劲，刷新你的页面。我每天推送多个更新，你可能需要刷新才能获得最新版本",
    "Royal favor unlocks Quality of Life upgrades and other useful features": "皇家青睐解锁生活质量升级和其他有用的功能",
    "Shift click to consume potions. Potions with battle effects can be stacked to increase the duration of effect": "Shift点击消耗药水。具有战斗效果的药剂可以堆叠以增加效果的持续时间",
    "Smelt your ores into bars and then use those to forge yourself gear": "将矿石冶炼成棒状，然后用这些来锻造自己的装备",
    "Some fishing locations have rare drops to be used in other skills": "一些钓鱼地点有稀有的掉落物用于其他技能",
    "Some trees drop other useful items to be used in other skills": "有些树会掉落其他有用的道具用于其他技能",
    "Starting at StarSteel there is a 10% chance your armor and equipment will be crafted into the rare variant with increased stats": "从星钢开始，你的盔甲和装备有10%的几率会被制作成稀有的变种，并增加属性",
    "Starting out, cooking is manual. drag a fish and hold until it is in the golden zone. Holding too long will burn the fish and too early leaves it raw": "一开始，烹饪是手工的。拖一条鱼，一直拖到黄金区域。放得太久会把鱼烤焦，放得太早又会生吃",
    "Strength increases the damage done to monsters": "力量增加对怪物造成的伤害",
    "To start, crafting items is one at a time. Batch cooking is unlocked in the camp": "首先，每次只能制作一件道具。在营地里，批量烹饪是没有锁的",
    "Tomes auto gather resources for you. Equip and stack them to increase the duration": "卷轴会自动为你收集资源。装备并堆叠它们以增加持续时间",
    "Tools do not have a rare variant": "工具没有稀有变体",
    "Unlock auto cooking with the camp fire": "解锁使用营火自动烹饪",
    "Unlock batch crafting in the camp with the crafting table": "在营地用制作桌解锁批量制作",
    "Unlock the Alchemy table in the camp to unlock batch alchemy": "解锁营地中的炼金术表可以解锁批量炼金术",
    "Unlock the camp with 325 total level and 10k gold": "总等级达到325级，10000金币解锁营地",
    "Upgrade them to increase their effect": "升级它们以增加它们的效果",
    "Use logs, planks, and other materials to construct buildings in your camp": "使用原木，木板和其他材料在你的营地建造建筑物",
    "Welcome to RuneCut. The Incremental Skilling RPG": "欢迎来到 符文切割放置。增量技能RPG",
    "Neko": "涅克",
    "A nimble blade-dancing cat with quick paws and sharper instincts. Swift, precise, and always landing on its feet.": "敏捷的舞剑猫，爪子敏捷，本能敏锐。敏捷，精准，而且总是用脚着地。",
    "Auto-cooking Bluefin Tuna —": "自动烹饪 蓝鳍金枪鱼 -",
    "🌿 Vine Horror": "🌿 藤蔓恐怖",
    "Vine Horror": "藤蔓恐怖",
    "Cut the vines! (x": "砍掉藤蔓! (x",
    "Abyssal Hellion": "深海恶灵",
    "Ruby": "红宝石",
    "Runed Coil": "符文线圈",
    "Runewood": "符文木",
    "Sapphire": "蓝宝石",
    "Splash": "溅射",
    "Starstone": "星石",
    "Auto-cooking Shrimps —": "自动烹饪 虾 —",
    "Elderwood": "接骨木",
    "Diamond": "钻石",
    "🌽 Farming": "🌽 农场",
    "You and Neko": "你和涅克",
    "— gold": "— 金币",
    "Locked": "未解锁",
    "Farming": "农业",
    "Buy": "购买",
    "🌾 Farming": "🌾 农业",
    "- Full Farming Functionality coming soon -": "- 完整的农场功能即将到来 -",
    "Plant": "种植",
    "Sturgeon Depths": "鲟鱼深处",
    "You have no seeds.": "你还没有种子。",
    "🛒 Farm Store": "🛒 农场商店",
    "Started auto-mining… at Draconyx Vein.": "开始自动采矿...在龙爪矿脉。",
    "Toxic Poison": "毒药",
    "Weapon Poison": "武器药水",
    "Beet": "甜菜",
    "Choose a seed to plant.": "请选择一个种子以种植。",
    "Growing": "生长中",
    "Ready to harvest!": "已成熟待收割!",
    "Ember": "余烬",
    "Leaf Dart": "叶镖",
    "Small Ground Spirit": "小大地精灵",
    "Small Fire Spirit": "小火焰精灵",
    "Small Forest Spirit": "小森林精灵",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Acc": "精准",
    "Hammer": "锤",
    "Greaves": "护胫",
    "Weapon": "武器",
    "Rod": "竿",
    "Ring": "戒指",
    "Boots": "靴子",
    "Dagger": "匕首",
    "Gloves": "手套",
    "Rock ": "矿石",
    "Platelegs": "板腿",
    "Platebody": "板甲",
    "Helm": "头盔",
    "Pickaxe": "镐",
    "Upgrade Bar": "升级锭",
    "Sword": "剑",
    "Shield": "盾",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "×": "×",
    "⚒️": "⚒️",
    "⚔️": "⚔️",
    "⛏️": "⛏️",
    "✕": "✕",
    "🍖": "🍖",
    "🍳": "🍳",
    "🎣": "🎣",
    "👑": "👑",
    "👖": "👖",
    "💍": "💍",
    "💪": "💪",
    "💾": "💾",
    "📖": "📖",
    "📿": "📿",
    "🔥": "🔥",
    "🗡️": "🗡️",
    "🥾": "🥾",
    "🧣": "🧣",
    "🧤": "🧤",
    "🧥": "🧥",
    "🪓": "🪓",
    "🪖": "🪖",
    "🪚": "🪚",
    "🛡️": "🛡️",
    "—": "—",
    "?": "?",
    "·": "·",
    "🪙": "🪙",
    "✓": "✓",
    "🏕️": "🏕️",
    "💚": "💚",
    "🧪": "🧪",
    "🪄": "🪄",
    "🛢️": "🛢️",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "+": "+",
    ".": ".",
    "…": "…",
    ":": ":",
    "-": "-",
    "|": "|",
    "(": "(",
    ")": ")",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    'a': 'a',
    'b': 'b',
    'c': 'c',
    'd': 'd',
    'e': 'e',
    'f': 'f',
    'g': 'g',
    'h': 'h',
    'i': 'i',
    'j': 'j',
    'k': 'k',
    'l': 'l',
    'm': 'm',
    'n': 'n',
    'o': 'o',
    'p': 'p',
    'q': 'q',
    'r': 'r',
    's': 's',
    't': 't',
    'u': 'u',
    'v': 'v',
    'w': 'w',
    'x': 'x',
    'y': 'y',
    'z': 'z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Animations: ": "动画: ",
    "Current Endgame: ": "当前终局: ",
    "Space Background: ": "太空背景: ",
    "Blacksteel Bar — Lv ": "黑钢锭 — 等级 ",
    "Steel Bar — Lv ": "钢锭 — 等级 ",
    "Bronze Bar — Lv ": "青铜锭 — 等级 ",
    "Iron Bar — Lv ": "铁锭 — 等级 ",
    "Copper Bar — Lv ": "铜锭 — 等级 ",
    "Glass Glob — Lv ": "玻璃球 — 等级 ",
    "Attack — Lv ": "攻击 — 等级 ",
    "Fishing — Lv ": "钓鱼 — 等级 ",
    "Destruction — Lv ": "破坏 — 等级 ",
    "Smithing — Lv ": "锻造 — 等级 ",
    "Cooking — Lv ": "烹饪 — 等级 ",
    "Royal Service — Lv ": "皇家服务 — 等级 ",
    "Crafting — Lv ": "制作 — 等级 ",
    "constructionBarMini — Lv ": "建筑锭最低 — 等级 ",
    "Construction — Lv ": "建筑— 等级 ",
    "Enchanting — Lv ": "强化 — 等级 ",
    "Woodcutting — Lv ": "伐木 — 等级 ",
    "Defense — Lv ": "防御 — 等级 ",
    "Alchemy — Lv ": "炼金 — 等级 ",
    "Strength — Lv ": "力量 — 等级 ",
    "Mining — Lv ": "采矿 — 等级 ",
    "Runewood Logs — yields ": "符文木 — 生产 ",
    "Elderwood Logs — yields ": "接骨木 — 生产 ",
    "Elderwood Logs  — yields ": "接骨木 — 生产 ",
    "Runewood Logs  — yields ": "符文木 — 生产 ",
    "Oak Logs — yields ": "橡木 — 生产 ",
    "Oak Logs  — yields ": "橡木 — 生产 ",
    "Birch Logs  — yields ": "桦木 — 生产 ",
    "Pine Logs  — yields ": "松木 — 生产 ",
    "Cedar Logs  — yields ": "雪松木 — 生产 ",
    "Maple Logs  — yields ": "枫木 — 生产 ",
    "Willow Logs  — yields ": "柳木 — 生产 ",
    "Yew Logs  — yields ": "紫杉木 — 生产 ",
    "Mining…": "采矿…",
    "Copper ": "铜",
    "Crafting": "制作",
    "Auto-mining…": "自动采矿...",
    "Smithing…": "锻造中...",
    "Chopping…": "砍树中...",
    "Brewing…": "酿造中...",
    "Forging Bronze Upgrade Bar…": "锻造青铜升级锭...",
    "Forging Bronze Axe…": "锻造青铜斧...",
    "Forging Bronze Gloves…": "锻造青铜手套...",
    "Forging Bronze Dagger…": "锻造青铜匕首...",
    "Forging Bronze Shield…": "锻造青铜盾...",
    "Forging Bronze Platelegs…": "锻造青铜板腿...",
    "Forging Bronze Platebody…": "锻造青铜板甲...",
    "Forging Bronze Pickaxe…": "锻造青铜镐...",
    "Forging Bronze Helm…": "锻造青铜头盔...",
    "Forging Bronze Sword…": "锻造青铜剑...",
    "Forging Bronze Boots…": "锻造青铜靴...",
    "Forging Copper Boots…": "锻造铜靴...",
    "Forging Copper Dagger…": "锻造铜匕首...",
    "Forging Copper Platebody": "锻造铜板甲...",
    "qty: ": "质量: ",
    "Swiftness": "迅捷",
    "Fish Pond Shallows — ": "在鱼塘浅滩钓鱼 - ",
    "Fishing… ": "钓鱼中...",
    "Cook Manta Ray — ": "烹饪蝠鲼 — ",
    "Cook Halibut — ": "烹饪大比目鱼 — ",
    "Cook Salmon — ": "烹饪鲑鱼 — ",
    "Cook Bluefin Tuna — ": "烹饪蓝鳍金枪鱼 — ",
    "Cook Eel — ": "烹饪鳗鱼 — ",
    "Cook Shrimps — ": "烹饪虾 — ",
    "Fish Abyssal Trench — ": "深渊海沟钓鱼 - ",
    "Fish Coast — ": "海岸钓鱼 - ",
    "Fish River — ": "河流钓鱼 - ",
    "Fish Open Ocean — ": "公海钓鱼 - ",
    "Fish River Bend — ": "河湾钓鱼 - ",
    "Cook Trout — ": "烹饪鳟鱼 — ",
    "Blacksteel ": "黑钢",
    "Bronze ": "青铜",
    "Iron ": "铁",
    "Steel ": "钢",
    "Speed: ": "速度: ",
    "Fish Marsh — ": "在沼泽钓鱼 - ",
    "Loot: ": "战利品: ",
    "Auto-cook ": "自动烹饪 ",
    "Mana spent: ": "法力消耗: ",
    "Version: ": "版本: ",
    "Next: ": "下一级: ",
    "Starsteel ": "星钢",
    "Rare Starsteel ": "稀有的星钢",
    "Pet level ": "宠物等级 ",
    "Victory! Pet XP ": "胜利! 宠物经验 ",
    "Smelting Copper Bar… ": "锻造青铜锭...",
    "Smelting Draconyx Bar… ": "锻造龙爪锭… ",
    "Unlock cost: ": "解锁成本: ",
    "Unlock (": "解锁 (",
    "Draconyx ": "龙爪",
    "Farming — Lv ": "农业 — 等级 ",
    "Corn Seeds": "玉米种子",
    "Beet Seeds": "甜菜种子",
    "Pumpkin Seeds": "南瓜种子",
    "Growing — ": "生长中 — ",
    "Harvest (": "收获 (",
    " (Lvl ": " (等级 ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    " total xp": " 总经验",
    " this level": " 本级",
    " xp to next": " 经验值到下一级",
    " (Wpn)": " (武器)",
    " — no xp": " - 无经验",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)$/,
    /^×([\d\.]+)$/,
    /^x([\d\.]+)$/,
    /^v([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)×$/,
    /^ ([\d\.]+)\%$/,
    /^… ([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^\[([\d\.]+):([\d\.]+):([\d\.]+)\]$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+) Sp$/,
    /^([\d\.]+) Oc$/,
    /^([\d\.]+) Dc$/,
    /^([\d\.]+) UDc$/,
    /^([\d\.]+) No$/,
    /^([\d\.]+) Sx$/,
    /^([\d\.]+) QaDc$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^×([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//字母加数字：([\d\.]+[A-Za-z])
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
//&nbsp;空格：\xA0
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^You found: (.+) Diamond$/, '你发现了: $1 钻石'],
    [/^You found: (.+) Emerald$/, '你发现了: $1 翡翠'],
    [/^You found: (.+) Ruby$/, '你发现了: $1 红宝石'],
    [/^You found: (.+) Starstone$/, '你发现了: $1 星石'],
    [/^You found: (.+) Sapphire$/, '你发现了: $1 蓝宝石'],
    [/^Buff: (.+) hit chance for (.+)$/, '增益: $1 命中率持续 $2'],
    [/^Buff: (.+) enemy damage for (.+)$/, '增益: $1 敌人伤害持续 $2'],
    [/^Upgraded Bronze Shield: qty: (.+) → qty: (.+) \((.+) Smithing xp\) \((.+) Bronze Upgrade Bar\)$/, '升级了青铜盾: 质量: $1 → 质量: $2 ($3 锻造经验) ($4 青铜升级锭)'],
    [/^Upgraded Bronze Gloves: qty: (.+) → qty: (.+) \((.+) Smithing xp\) \((.+) Bronze Upgrade Bar\)$/, '升级了青铜手套: 质量: $1 → 质量: $2 ($3 锻造经验) ($4 青铜升级锭)'],
    [/^Upgraded Iron Gloves: qty: (.+) → qty: (.+) \((.+) Smithing xp\) \((.+) Iron Upgrade Bar\)$/, '升级了铁手套: 质量: $1 → 质量: $2 ($3 锻造经验) ($4 铁升级锭)'],
    [/^Upgraded Iron Boots: qty: (.+) → qty: (.+) \((.+) Smithing xp\) \((.+) Iron Upgrade Bar\)$/, '升级了铁靴子: 质量: $1 → 质量: $2 ($3 锻造经验) ($4 铁升级锭)'],
    [/^Upgraded Iron Greaves: qty: (.+) → qty: (.+) \((.+) Smithing xp\) \((.+) Iron Upgrade Bar\)$/, '升级了铁护胫: 质量: $1 → 质量: $2 ($3 锻造经验) ($4 铁升级锭)'],
    [/^Upgraded Iron Helm: qty: (.+) → qty: (.+) \((.+) Smithing xp\) \((.+) Iron Upgrade Bar\)$/, '升级了铁头盔: 质量: $1 → 质量: $2 ($3 锻造经验) ($4 铁升级锭)'],
    [/^Upgraded Iron Plate: qty: (.+) → qty: (.+) \((.+) Smithing xp\) \((.+) Iron Upgrade Bar\)$/, '升级了铁板甲: 质量: $1 → 质量: $2 ($3 锻造经验) ($4 铁升级锭)'],
    [/^Upgraded Iron Shield: qty: (.+) → qty: (.+) \((.+) Smithing xp\) \((.+) Iron Upgrade Bar\)$/, '升级了铁盾牌: 质量: $1 → 质量: $2 ($3 锻造经验) ($4 铁升级锭)'],
    [/^Upgraded Iron Sword: qty: (.+) → qty: (.+) \((.+) Smithing xp\) \((.+) Iron Upgrade Bar\)$/, '升级了铁剑: 质量: $1 → 质量: $2 ($3 锻造经验) ($4 铁升级锭)'],
    [/^You defeated (.+)!$/, '你击败了 $1！'],
    [/^You engage (.+)!$/, '你与 $1 交战！'],
    [/^Your pet engages (.+)!$/, '你的宠物与 $1 交战！'],
    [/^You were defeated by (.+).$/, '你被 $1 击败了。'],
    [/^You miss (.+).$/, '你未命中 $1。'],
    [/^(.+) misses you.$/, '$1 未命中你。'],
    [/^(.+) hits you for ([\d\.,]+).$/, '$1 击中你并造成了 $2 伤害。'],
    [/^You hit (.+) for ([\d\.,]+).$/, '你击中了 $1 并造成了 $2 伤害。'],
    [/^Plate · qty: (.+) \— Equipped \(body\)$/, '板甲 · 质量: $1 — 已装备 (身体)'],
    [/^Boots · qty: (.+) \— Equipped \(boots\)$/, '靴子 · 质量: $1 — 已装备 (靴子)'],
    [/^Dagger · qty: (.+) \— Equipped \(weapon\)$/, '匕首 · 质量: $1 — 已装备 (武器)'],
    [/^Helm · qty: (.+) \— Equipped \(head\)$/, '头盔 · 质量: $1 — 已装备 (头部)'],
    [/^Shield · qty: (.+) \— Equipped \(shield\)$/, '盾牌 · 质量: $1 — 已装备 (盾牌)'],
    [/^Gloves · qty: (.+) \— Equipped \(gloves\)$/, '手套 · 质量: $1 — 已装备 (手套)'],
    [/^Greaves · qty: (.+) \— Equipped \(legs\)$/, '护胫 · 质量: $1 — 已装备 (腿部)'],
    [/^Plate · qty: (.+) \— Inventory$/, '板甲 · 质量: $1 — 库存'],
    [/^Dagger · qty: (.+) \— Inventory$/, '匕首 · 质量: $1 — 库存'],
    [/^hammer · qty: (.+) \— Inventory$/, '锤 · 质量: $1 — 库存'],
    [/^Boots · qty: (.+) \— Inventory$/, '靴子 · 质量: $1 — 库存'],
    [/^Gloves · qty: (.+) \— Inventory$/, '手套 · 质量: $1 — 库存'],
    [/^Helm · qty: (.+) \— Inventory$/, '头盔 · 质量: $1 — 库存'],
    [/^Shield · qty: (.+) \— Inventory$/, '盾牌 · 质量: $1 — 库存'],
    [/^Sword · qty: (.+) \— Inventory$/, '剑 · 质量: $1 — 库存'],
    [/^Greaves · qty: (.+) \— Inventory$/, '护胫 · 质量: $1 — 库存'],
    [/^Qty: (.+) · (.+) ea · Total: (.+)$/, '质量: $1 · $2 价值 · 总计: $3'],
    [/^Qty: (.+) · (.+)g · Total: (.+)$/, '质量: $1 · $2g · 总计: $3'],
    [/^Qty: (.+) · (.+)g$/, '质量: $1 · $2g'],
    [/^Qty: (.+) · (.+) ea$/, '质量: $1 · $2 价值'],
    [/^Forged Bronze Dagger · qty: (.+) → (.+) Smithing xp$/, '锻造青铜匕首 · 质量: $1 → $2 锻造经验'],
    [/^Forged Bronze Greaves · qty: (.+) → (.+) Smithing xp$/, '锻造青铜护胫 · 质量: $1 → $2 锻造经验'],
    [/^Forged Bronze Upgrade Bar → (.+) Smithing xp$/, '锻造青铜升级锭 → $1 锻造经验'],
    [/^Forged Bronze Axe → (.+) Smithing xp$/, '锻造青铜斧 → $1 锻造经验'],
    [/^Forged Bronze Helm · qty: (.+) → (.+) Smithing xp$/, '锻造青铜头盔 · 质量: $1 → $2 锻造经验'],
    [/^Forged Bronze hammer · qty: (.+) → (.+) Smithing xp$/, '锻造青铜锤 · 质量: $1 → $2 锻造经验'],
    [/^Forged Bronze Pick · qty: (.+) → (.+) Smithing xp$/, '锻造青铜镐 · 质量: $1 → $2 锻造经验'],
    [/^Forged Bronze Sword · qty: (.+) → (.+) Smithing xp$/, '锻造青铜剑 · 质量: $1 → $2 锻造经验'],
    [/^Forged Bronze Shield · qty: (.+) → (.+) Smithing xp$/, '锻造青铜盾 · 质量: $1 → $2 锻造经验'],
    [/^Forged Bronze Plate · qty: (.+) → (.+) Smithing xp$/, '锻造青铜板甲 · 质量: $1 → $2 锻造经验'],
    [/^Forged Bronze Gloves · qty: (.+) → (.+) Smithing xp$/, '锻造青铜手套 · 质量: $1 → $2 锻造经验'],
    [/^Forged Bronze Boots · qty: (.+) → (.+) Smithing xp$/, '锻造青铜靴 · 质量: $1 → $2 锻造经验'],
    [/^Forged Copper Boots · qty: (.+) → (.+) Smithing xp$/, '锻造铜靴 · 质量: $1 → $2 锻造经验'],
    [/^Forged Copper Dagger · qty: (.+) → (.+) Smithing xp$/, '锻造铜匕首 · 质量: $1 → $2 锻造经验'],
    [/^Forged Copper Gloves · qty: (.+) → (.+) Smithing xp$/, '锻造铜手套 · 质量: $1 → $2 锻造经验'],
    [/^Forged Copper Greaves · qty: (.+) → (.+) Smithing xp$/, '锻造铜护胫 · 质量: $1 → $2 锻造经验'],
    [/^Forged Copper Helm · qty: (.+) → (.+) Smithing xp$/, '锻造铜头盔 · 质量: $1 → $2 锻造经验'],
    [/^Forged Copper Plate · qty: (.+) → (.+) Smithing xp$/, '锻造铜板甲 · 质量: $1 → $2 锻造经验'],
    [/^Forged Copper Pick → (.+) Smithing xp$/, '锻造铜镐子 → $1 锻造经验'],
    [/^Forged Copper Upgrade Bar → (.+) Smithing xp$/, '锻造铜升级锭 → $1 锻造经验'],
    [/^Forged Copper hammer · qty: (.+) → (.+) Smithing xp$/, '锻造铜锤 · 质量: $1 → $2 锻造经验'],
    [/^Forged Copper Shield · qty: (.+) → (.+) Smithing xp$/, '锻造铜盾牌 · 质量: $1 → $2 锻造经验'],
    [/^Forged Steel Dagger · qty: (.+) → (.+) Smithing xp$/, '锻造钢匕首 · 质量: $1 → $2 锻造经验'],
    [/^Forged Steel Greaves · qty: (.+) → (.+) Smithing xp$/, '锻造钢护胫 · 质量: $1 → $2 锻造经验'],
    [/^Forged Steel Upgrade Bar → (.+) Smithing xp$/, '锻造钢升级锭 → $1 锻造经验'],
    [/^Forged Steel Axe → (.+) Smithing xp$/, '锻造钢斧 → $1 锻造经验'],
    [/^Forged Steel Helm · qty: (.+) → (.+) Smithing xp$/, '锻造钢头盔 · 质量: $1 → $2 锻造经验'],
    [/^Forged Steel hammer · qty: (.+) → (.+) Smithing xp$/, '锻造钢锤 · 质量: $1 → $2 锻造经验'],
    [/^Forged Steel Pick · qty: (.+) → (.+) Smithing xp$/, '锻造钢镐 · 质量: $1 → $2 锻造经验'],
    [/^Forged Steel Sword · qty: (.+) → (.+) Smithing xp$/, '锻造钢剑 · 质量: $1 → $2 锻造经验'],
    [/^Forged Steel Shield · qty: (.+) → (.+) Smithing xp$/, '锻造钢盾 · 质量: $1 → $2 锻造经验'],
    [/^Forged Steel Plate · qty: (.+) → (.+) Smithing xp$/, '锻造钢板甲 · 质量: $1 → $2 锻造经验'],
    [/^Forged Steel Gloves · qty: (.+) → (.+) Smithing xp$/, '锻造钢手套 · 质量: $1 → $2 锻造经验'],
    [/^Forged Steel Boots · qty: (.+) → (.+) Smithing xp$/, '锻造钢靴 · 质量: $1 → $2 锻造经验'],
    [/^Forged Iron Dagger · qty: (.+) → (.+) Smithing xp$/, '锻造铁匕首 · 质量: $1 → $2 锻造经验'],
    [/^Forged Iron Greaves · qty: (.+) → (.+) Smithing xp$/, '锻造铁护胫 · 质量: $1 → $2 锻造经验'],
    [/^Forged Iron Upgrade Bar → (.+) Smithing xp$/, '锻造铁升级锭 → $1 锻造经验'],
    [/^Forged Iron Axe → (.+) Smithing xp$/, '锻造铁斧 → $1 锻造经验'],
    [/^Forged Iron Helm · qty: (.+) → (.+) Smithing xp$/, '锻造铁头盔 · 质量: $1 → $2 锻造经验'],
    [/^Forged Iron hammer · qty: (.+) → (.+) Smithing xp$/, '锻造铁锤 · 质量: $1 → $2 锻造经验'],
    [/^Forged Iron Pick · qty: (.+) → (.+) Smithing xp$/, '锻造铁镐 · 质量: $1 → $2 锻造经验'],
    [/^Forged Iron Sword · qty: (.+) → (.+) Smithing xp$/, '锻造铁剑 · 质量: $1 → $2 锻造经验'],
    [/^Forged Iron Shield · qty: (.+) → (.+) Smithing xp$/, '锻造铁盾 · 质量: $1 → $2 锻造经验'],
    [/^Forged Iron Plate · qty: (.+) → (.+) Smithing xp$/, '锻造铁板甲 · 质量: $1 → $2 锻造经验'],
    [/^Forged Iron Gloves · qty: (.+) → (.+) Smithing xp$/, '锻造铁手套 · 质量: $1 → $2 锻造经验'],
    [/^Forged Iron Boots · qty: (.+) → (.+) Smithing xp$/, '锻造铁靴 · 质量: $1 → $2 锻造经验'],
    [/^Forged Starsteel Dagger · qty: (.+) → (.+) Smithing xp$/, '锻造星钢匕首 · 质量: $1 → $2 锻造经验'],
    [/^Forged Starsteel Greaves · qty: (.+) → (.+) Smithing xp$/, '锻造星钢护胫 · 质量: $1 → $2 锻造经验'],
    [/^Forged Starsteel Upgrade Bar → (.+) Smithing xp$/, '锻造星钢升级锭 → $1 锻造经验'],
    [/^Forged Starsteel Axe → (.+) Smithing xp$/, '锻造星钢斧 → $1 锻造经验'],
    [/^Forged Starsteel Helm · qty: (.+) → (.+) Smithing xp$/, '锻造星钢头盔 · 质量: $1 → $2 锻造经验'],
    [/^Forged Starsteel hammer · qty: (.+) → (.+) Smithing xp$/, '锻造星钢锤 · 质量: $1 → $2 锻造经验'],
    [/^Forged Starsteel Pick · qty: (.+) → (.+) Smithing xp$/, '锻造星钢镐 · 质量: $1 → $2 锻造经验'],
    [/^Forged Starsteel Sword · qty: (.+) → (.+) Smithing xp$/, '锻造星钢剑 · 质量: $1 → $2 锻造经验'],
    [/^Forged Starsteel Shield · qty: (.+) → (.+) Smithing xp$/, '锻造星钢盾 · 质量: $1 → $2 锻造经验'],
    [/^Forged Starsteel Plate · qty: (.+) → (.+) Smithing xp$/, '锻造星钢板甲 · 质量: $1 → $2 锻造经验'],
    [/^Forged Starsteel Gloves · qty: (.+) → (.+) Smithing xp$/, '锻造星钢手套 · 质量: $1 → $2 锻造经验'],
    [/^Forged Starsteel Boots · qty: (.+) → (.+) Smithing xp$/, '锻造星钢靴 · 质量: $1 → $2 锻造经验'],
    [/^Forged Starsteel Dagger → (.+) Smithing xp$/, '锻造星钢匕首 → $1 锻造经验'],
    [/^Forged Starsteel Greaves → (.+) Smithing xp$/, '锻造星钢护胫 → $1 锻造经验'],
    [/^Forged Starsteel Upgrade Bar → (.+) Smithing xp$/, '锻造星钢升级锭 → $1 锻造经验'],
    [/^Forged Starsteel Axe → (.+) Smithing xp$/, '锻造星钢斧 → $1 锻造经验'],
    [/^Forged Starsteel Helm → (.+) Smithing xp$/, '锻造星钢头盔 → $1 锻造经验'],
    [/^Forged Starsteel hammer → (.+) Smithing xp$/, '锻造星钢锤 → $1 锻造经验'],
    [/^Forged Starsteel Pick → (.+) Smithing xp$/, '锻造星钢镐 → $1 锻造经验'],
    [/^Forged Starsteel Sword → (.+) Smithing xp$/, '锻造星钢剑 → $1 锻造经验'],
    [/^Forged Starsteel Shield → (.+) Smithing xp$/, '锻造星钢盾 → $1 锻造经验'],
    [/^Forged Starsteel Plate → (.+) Smithing xp$/, '锻造星钢板甲 → $1 锻造经验'],
    [/^Forged Starsteel Gloves → (.+) Smithing xp$/, '锻造星钢手套 → $1 锻造经验'],
    [/^Forged Starsteel Boots → (.+) Smithing xp$/, '锻造星钢靴 → $1 锻造经验'],
    [/^Smelted Starsteel Bar → (.+) Smithing xp$/, '锻造星钢锭 → $1 锻造经验'],
    [/^Smelted Bronze Bar → (.+) Smithing xp$/, '锻造青铜锭 → $1 锻造经验'],
    [/^Smelted Iron Bar → (.+) Smithing xp$/, '锻造铁锭 → $1 锻造经验'],
    [/^Smelted Copper Bar → (.+) Smithing xp$/, '锻造铜锭 → $1 锻造经验'],
    [/^Smelted Glass Glob → (.+) Smithing xp$/, '锻造玻璃球 → $1 锻造经验'],
    [/^Forged Copper Axe → (.+) Smithing xp$/, '锻造铜斧 → $1 锻造经验'],
    [/^Enchanted Apprentice Forest Tome → (.+) Enchanting xp$/, '附魔学徒海洋卷轴 → $1 强化经验'],
    [/^Enchanted Apprentice Sea Tome → (.+) Enchanting xp$/, '附魔学徒海洋卷轴 → $1 强化经验'],
    [/^Enchanted Apprentice Rock Tome → (.+) Enchanting xp$/, '附魔学徒岩石卷轴 → $1 强化经验'],
    [/^Enchanted Novice Forest Tome → (.+) Enchanting xp$/, '附魔新手森林卷轴 → $1 强化经验'],
    [/^Enchanted Novice Sea Tome → (.+) Enchanting xp$/, '附魔新手海洋卷轴 → $1 强化经验'],
    [/^Enchanted Novice Rock Tome → (.+) Enchanting xp$/, '附魔新手岩石卷轴 → $1 强化经验'],
    [/^Enchanted tome_rock_advanced → (.+) enchant xp$/, '附魔高级岩石卷轴 → $1 强化经验'],
    [/^Enchanted Quicksilver\(e\) → (.+) Enchanting xp$/, '附魔水银 → $1 强化经验'],
    [/^Crafted Book → (.+) craft xp$/, '制作书 → $1 制作经验'],
    [/^Crafted Fishing Pole → (.+) craft xp$/, '制作鱼竿 → $1 制作经验'],
    [/^Crafted Glass Vial → (.+) craft xp$/, '制作玻璃小瓶 → $1 制作经验'],
    [/^Crafted Pine Planks → (.+) craft xp$/, '制作松木板 → $1 制作经验'],
    [/^Crafted Birch Planks → (.+) craft xp$/, '制作桦木板 → $1 制作经验'],
    [/^Crafted Cedar Planks → (.+) craft xp$/, '制作雪松木板 → $1 制作经验'],
    [/^Crafted Willow Planks → (.+) craft xp$/, '制作柳木板 → $1 制作经验'],
    [/^Crafted Reinforced Vial → (.+) craft xp$/, '制作加强小瓶 → $1 制作经验'],
    [/^Crafted Sturdy Pole → (.+) craft xp$/, '制作坚固的杆 → $1 制作经验'],
    [/^Crafted Nails → (.+) craft xp$/, '制作钉子 → $1 制作经验'],
    [/^Crafted Pages → (.+) craft xp$/, '制作纸 → $1 制作经验'],
    [/^Crafted Oak Planks → (.+) craft xp$/, '制作橡木板 → $1 制作经验'],
    [/^Crafted Wood Handle → (.+) craft xp$/, '制作木柄 → $1 制作经验'],
    [/^Crafted Advanced Defense → (.+) alch xp$/, '制作高级防御 → $1 炼金经验'],
    [/^Crafted Nails \(x(.+)\) → (.+) craft xp, (.+) construction xp$/, '制作钉子 (x$1) → $2 制作, $3 建筑经验'],
    [/^Chopped Pond Shallows → (.+) Raw Shrimp · Forestry (.+) xp$/, '在池塘浅滩砍树 → $1 生虾 · $2 林业经验'],
    [/^Caught Raw Shrimp at Pond Shallows → (.+) Raw Shrimp · (.+) Fishing xp$/, '在池塘浅滩捕获生虾 → $1 生虾 · $2 钓鱼经验'],
    [/^Caught Raw Eel at Marsh → (.+) Raw Eel · (.+) Sea Essence · (.+) Fishing xp$/, '在沼泽捕捉生鳗鱼 → $1 生鳗鱼 · $2 海洋精华 · $3 钓鱼经验'],
    [/^Caught Raw Eel at Marsh → (.+) Raw Eel · (.+) Fishing xp$/, '在沼泽捕捉生鳗鱼 → $1 生鳗鱼 · $2 钓鱼经验'],
    [/^Caught Raw Salmon at River → (.+) Raw Salmon · (.+) Sea Essence · (.+) Fishing xp$/, '在河流捕获生鲑鱼 → $1 生鲑鱼 · $2 海洋精华 · $3 钓鱼经验'],
    [/^Caught Raw Salmon at River → (.+) Raw Salmon · (.+) Fishing xp$/, '在河流捕获生鲑鱼 → $1 生鲑鱼 · $2 钓鱼经验'],
    [/^Caught Raw Angler at Abyssal Trench → (.+) Raw Angler · (.+) Sea Essence · (.+) Fishing xp$/, '在深渊海沟捕获生琵琶鱼 → $1 生琵琶鱼 · $2 海洋精华 · $3 钓鱼经验'],
    [/^Caught Raw Angler at Abyssal Trench → (.+) Raw Angler · (.+) Fishing xp$/, '在深渊海沟捕获生琵琶鱼 → $1 生琵琶鱼 · $2 钓鱼经验'],
    [/^Caught Bluewater Run → (.+) Raw Bluefin Tuna · (.+) Sea Essence · (.+) Fishing xp$/, '在蓝水湾捕鱼 → $1 生蓝鳍金枪鱼 · $2 海洋精华 · $3 钓鱼经验'],
    [/^Caught Bluewater Run → (.+) Raw Bluefin Tuna · (.+) Fishing xp$/, '在蓝水湾捕鱼 → $1 生蓝鳍金枪鱼 · $2 钓鱼经验'],
    [/^Caught Raw Trout at River Bend → (.+) Raw Trout · (.+) Sea Essence · (.+) Fishing xp$/, '在河湾捕捉生鳟鱼 → $1 生鳟鱼 · $2 海洋精华 · $3 钓鱼经验'],
    [/^Caught Raw Manta Ray at Open Ocean → (.+) Raw Manta Ray · (.+) Sea Essence · (.+) Fishing xp$/, '在公海捕捉生蝠鲼 → $1 生蝠鲼 · $2 海洋精华 · $3 钓鱼经验'],
    [/^Caught Raw Manta Ray at Open Ocean → (.+) Raw Manta Ray · (.+) Fishing xp$/, '在公海捕捉生蝠鲼 → $1 生蝠鲼 · $2 钓鱼经验'],
    [/^Caught Raw Halibut at Coast → (.+) Raw Halibut · (.+) Sea Essence · (.+) Fishing xp$/, '在海岸捕捉大比目鱼 → $1 生大比目鱼 · $2 海洋精华 · $3 钓鱼经验'],
    [/^Caught Raw Halibut at Coast → (.+) Raw Halibut · (.+) Fishing xp$/, '在海岸捕捉大比目鱼 → $1 生大比目鱼 · $2 钓鱼经验'],
    [/^Caught Raw Trout at River Bend → (.+) Raw Trout · (.+) Fishing xp$/, '在河湾捕捉生鳟鱼 → $1 生鳟鱼 · $2 钓鱼经验'],
    [/^Caught Asterium Ore at Asterium Cluster → (.+) Asterium Ore · (.+) Fishing xp$/, '在星宿簇捕捉星宿矿石 → $1 星宿矿石 · $2 钓鱼经验'],
    [/^Mined Draconyx Vein → (.+) Draconyx Ore · (.+) Rock Essence · Mining (.+) xp$/, '开采龙爪矿脉 → $1 龙爪矿石 · $2 岩石精华 · 采矿 $3 经验值'],
    [/^Mined Draconyx Vein → (.+) Draconyx Ore · (.+) Mining xp$/, '开采龙爪矿脉 → $1 龙爪矿石 · $2 采矿经验值'],
    [/^Mined Asterium Cluster → (.+) Asterium Ore · (.+) Rock Essence · Mining (.+) xp$/, '开采星宿簇 → $1 星宿矿石 · $2 岩石精华 · 采矿 $3 经验值'],
    [/^Mined Asterium Cluster → (.+) Asterium Ore · Mining (.+) xp$/, '开采星宿簇 → $1 星宿矿石 · 采矿 $2 经验值'],
    [/^Mined Coal Bed → (.+) Coal · (.+) Rock Essence · Mining (.+) xp$/, '开采煤床 → $1 煤 · $2 岩石精华 · 采矿 $3 经验值'],
    [/^Mined Coal Bed → (.+) Coal · Mining (.+) xp$/, '开采煤床 → $1 煤 · 采矿 $2 经验值'],
    [/^Mined Nightiron Vein → (.+) Nightiron Ore · (.+) Rock Essence · Mining (.+) xp$/, '开采夜铁矿脉 → $1 夜铁矿石 · $2 岩石精华 · 采矿 $3 经验值'],
    [/^Mined Nightiron Vein → (.+) Nightiron Ore · Mining (.+) xp$/, '开采夜铁矿脉 → $1 夜铁矿石 · 采矿 $2 经验值'],
    [/^Mined Sand Vein → (.+) Silica Sand · (.+) Rock Essence · Mining (.+) xp$/, '开采砂脉 → $1 硅砂 · $2 岩石精华 · 采矿 $3 经验值'],
    [/^Mined Sand Vein → (.+) Silica Sand · Mining (.+) xp$/, '开采砂脉 → $1 硅砂 · 采矿 $2 经验值'],
    [/^Mined Copper Rock → (.+) Copper Ore · (.+) Rock Essence · Mining (.+) xp$/, '开采铜岩 → $1 铜矿石 · $2 岩石精华 · 采矿 $3 经验值'],
    [/^Mined Iron Deposit → (.+) Iron Ore · (.+) Rock Essence · Mining (.+) xp$/, '开采铁矿床 → $1 铁矿石 · $2 岩石精华 · 采矿 $3 经验值'],
    [/^Mined Iron Deposit → (.+) Iron Ore · (.+) Rock Essence · (.+) Mining xp$/, '开采铁矿床 → $1 铁矿石 · $2 岩石精华 · $3 采矿经验值'],
    [/^Mined Iron Deposit → (.+) Iron Ore · (.+) Mining xp$/, '开采铁矿床 → $1 铁矿石 · $2 采矿经验值'],
    [/^Mined Copper Rock → (.+) Copper Ore · Mining (.+) xp$/, '开采铜岩 → $1 铜矿石 · 采矿 $2 经验值'],
    [/^Mined Tin Seam → (.+) Tin Ore · (.+) Rock Essence · Mining (.+) xp$/, '开采锡矿层 → $1 锡矿石 · $2 岩石精华 · 采矿 $3 经验值'],
    [/^Mined Tin Seam → (.+) Tin Ore · Mining (.+) xp$/, '开采锡矿层 → $1 锡矿石 · 采矿 $2 经验值'],
    [/^Mined Cedar → (.+) Cedar Logs · Mining (.+) xp$/, '开采雪松 → $1 雪松原木 · 采矿 $2 经验值'],
    [/^Mined Iron Deposit → (.+) Iron Ore · Mining (.+) xp$/, '开采铁矿床 → $1 铁矿石 · 采矿 $2 经验值'],
    [/^Cooked ([\d\.,]+)× Shrimps → (.+) Cooking xp$/, '烹饪 $1× 虾 → $2 烹饪经验值'],
    [/^Cooked ([\d\.,]+)× Eel → (.+) Cooking xp$/, '烹饪 $1× 鳗鱼 → $2 烹饪经验值'],
    [/^Cooked ([\d\.,]+)× Halibut → (.+) Cooking xp$/, '烹饪 $1× 大比目鱼 → $2 烹饪经验值'],
    [/^Cooked ([\d\.,]+)× Manta Ray → (.+) Cooking xp$/, '烹饪 $1× 蝠鲼 → $2 烹饪经验值'],
    [/^Cooked ([\d\.,]+)× Salmon → (.+) Cooking xp$/, '烹饪 $1× 鲑鱼 → $2 烹饪经验值'],
    [/^Cooked ([\d\.,]+)× Bluefin Tuna → (.+) Cooking xp$/, '烹饪 $1× 蓝鳍金枪鱼 → $2 烹饪经验值'],
    [/^Cooked ([\d\.,]+)× Shrimp → (.+) Cooking xp$/, '烹饪 $1× 虾 → $2 烹饪经验值'],
    [/^Cooked ([\d\.,]+)× Trout → (.+) Cooking xp$/, '烹饪 $1× 鳟鱼 → $2 烹饪经验值'],
    [/^Chopped Maple → (.+) Maple Logs · (.+) Forest Essence · Forestry (.+) xp$/, '砍枫树 → $1 枫木 · $2 森林精华 · 森林 $3 经验值'],
    [/^Chopped Maple → (.+) Maple Logs · Forestry (.+) xp$/, '砍枫树 → $1 枫木 · 森林 $2 经验值'],
    [/^Chopped Maple → (.+) Maple Logs · (.+) Forestry xp$/, '砍枫树 → $1 枫木 · $2 森林经验值'],
    [/^Chopped Birch → (.+) Birch Logs · (.+) Forest Essence · Forestry (.+) xp$/, '砍桦树 → $1 桦木 · $2 森林精华 · 森林 $3 经验值'],
    [/^Chopped Cedar → (.+) Cedar Logs · (.+) Forest Essence · Forestry (.+) xp$/, '砍雪松树 → $1 雪松木 · $2 森林精华 · 森林 $3 经验值'],
    [/^Chopped Willow → (.+) Willow Logs · (.+) Forest Essence · Forestry (.+) xp$/, '砍柳树 → $1 柳木 · $2 森林精华 · 森林 $3 经验值'],
    [/^Chopped Cedar → (.+) Cedar Logs · (.+) Forest Essence · (.+) Forestry xp$/, '砍雪松树 → $1 雪松原木 · $2 森林精华 · $3 森林经验值'],
    [/^Chopped Cedar → (.+) Cedar Logs · (.+) Forestry xp$/, '砍雪松树 → $1 雪松木 · $2 森林经验值'],
    [/^Chopped Yew → (.+) Yew Logs · (.+) Forest Essence · (.+) Forestry xp$/, '砍紫杉树 → $1 紫杉木 · $2 森林精华 · $3 森林经验值'],
    [/^Chopped Yew → (.+) Yew Logs · (.+) Forestry xp$/, '砍紫杉树 → $1 紫杉木 · $2 森林经验值'],
    [/^Chopped Oak → (.+) Oak Logs · (.+) Forest Essence · Forestry (.+) xp$/, '砍橡树 → $1 橡木 · $2 森林精华 · 森林 $3 经验值'],
    [/^Chopped Oak → (.+) Oak Logs · Forestry (.+) xp$/, '砍橡树 → $1 橡木 · 森林 $2 经验值'],
    [/^Chopped Birch → (.+) Birch Logs · Forestry (.+) xp$/, '砍桦树 → $1 桦木 · 森林 $2 经验值'],
    [/^Chopped Willow → (.+) Willow Logs · Forestry (.+) xp$/, '砍柳树 → $1 柳木 · 森林 $2 经验值'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
    [/^([\d\.]+)\/sec$/, '$1\/秒'],
    [/^([\d\.,]+)\/sec$/, '$1\/秒'],
    [/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^Greaves \(([\d\.]+)\%\)$/, '护胫 ($1\%)'],
    [/^Dagger \(([\d\.]+)\%\)$/, '匕首 ($1\%)'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+) Royal Service XP$/, '$1 皇家服务经验'],
    [/^([\d\.,]+)g$/, '$1g'],
    [/^([\d\.,]+) gold$/, '$1 金币'],
    [/^([\d\.,]+) gold\n         • Req: Farming Lvl ([\d\.,]+)$/, '$1 金币\n         • 需要: 农业 等级 $2'],
    [/^\+([\d\.,]+) Construction xp$/, '+$1 建造经验'],
    [/^\-([\d\.,]+) MP$/, '-$1 法力值'],
    [/^Chopped Pine → \+([\d\.,]+) Pine Logs · Forestry \+([\d\.,]+) xp$/, '砍松树 → +$1 松树原木 · 林业 +$2 经验'],
    [/^Chopped Pine → \+([\d\.,]+) Pine Logs · \+([\d\.,]+) Forest Essence · Forestry \+([\d\.,]+) xp$/, '砍松树 → +$1 松树原木 · +$2 林业精华 · 林业 +$3 经验'],
    [/^Consumed ([\d\.,]+)× Forest Essence$/, '消耗 $1× 森林精华'],
    [/^Consumed ([\d\.,]+)× Quicksilver$/, '消耗 $1× 水银'],
    [/^Consumed ([\d\.,]+)× Book$/, '消耗 $1× 书'],
    [/^Consumed ([\d\.,]+)× Sea Essence$/, '消耗 $1× 海洋精华'],
    [/^([\d\.,]+)× Quicksilver$/, '$1× 水银'],
    [/^([\d\.,]+)× Birch Logs$/, '$1× 桦木'],
    [/^([\d\.,]+)× Maple Logs$/, '$1× 枫木'],
    [/^([\d\.,]+)× Pine Logs$/, '$1× 松木'],
    [/^([\d\.,]+)× Pine Logs → ([\d\.,]+)× Pages$/, '$1× 松木 → $2× 纸'],
    [/^([\d\.,]+)× Maple Logs → ([\d\.,]+)× Pages$/, '$1× 枫木 → $2× 纸'],
    [/^([\d\.,]+)× Runewood Logs$/, '$1× 符文木'],
    [/^([\d\.,]+)× Willow Logs$/, '$1× 柳木'],
    [/^([\d\.,]+)× Yew Logs$/, '$1× 紫杉木'],
    [/^([\d\.,]+)× Cedar Logs$/, '$1× 雪松木'],
    [/^([\d\.,]+)× log elderwood$/, '$1× 原木接骨木'],
    [/^([\d\.,]+)× Elderwood Logs$/, '$1× 接骨木原木'],
    [/^([\d\.,]+)× Oak Logs$/, '$1× 橡木'],
    [/^([\d\.,]+)× Oak Plank · ([\d\.,]+)× Nails\nAFK \+([\d\.,]+)s$/, '$1× 橡木板 · $2× 钉子\n离开 +$3秒'],
    [/^([\d\.,]+)× Oak Logs\nAuto-cook \+([\d\.,]+)s$/, '$1× 橡木\n自动烹饪 +$2s'],
    [/^([\d\.,]+)× Pine Logs\nAuto-cook \+([\d\.,]+)s$/, '$1× 松木\n自动烹饪 +$2s'],
    [/^([\d\.,]+)× Book · ([\d\.,]+)× Sea Essence · ([\d\.,]+)× Mana$/, '$1× 书 · $2× 海洋精华 · $3× 法力'],
    [/^([\d\.,]+)× Book · ([\d\.,]+)× Rock Essence · ([\d\.,]+)× Mana$/, '$1× 书 · $2× 岩石精华 · $3× 法力'],
    [/^([\d\.,]+)× Book · ([\d\.,]+)× Forest Essence · ([\d\.,]+)× Mana$/, '$1× 书 · $2× 森林精华 · $3× 法力'],
    [/^([\d\.,]+)× Willow Logs → ([\d\.,]+)× Pages$/, '$1× 柳木 → $2× 纸'],
    [/^([\d\.,]+)× Maple Logs → ([\d\.,]+)× Crypt Cord$/, '$1× 枫木 → $2× 地穴绳'],
    [/^([\d\.,]+)× Oak Logs → ([\d\.,]+)× Pages$/, '$1× 橡木 → $2× 纸'],
    [/^([\d\.,]+)× Cedar Logs → ([\d\.,]+)× Pages$/, '$1× 雪松木 → $2× 纸'],
    [/^([\d\.,]+)× Birch Logs → ([\d\.,]+)× Pages$/, '$1× 桦木 → $2× 纸'],
    [/^([\d\.,]+)× Oak Logs, ([\d\.,]+)× Wire Coil$/, '$1× 橡木, $2× 线圈'],
    [/^([\d\.,]+)× Glass Glob, ([\d\.,]+)× Wire Coil$/, '$1× 玻璃球, $2× 线圈'],
    [/^([\d\.,]+)× Pages, ([\d\.,]+)× Leather$/, '$1× 纸, $2× 皮革'],
    [/^([\d\.,]+)× Quicksilver · ([\d\.,]+)× Mana$/, '$1× 水银 · $2× 法力'],
    [/^([\d\.,]+)× Pine Plank · ([\d\.,]+)× Nails\nAFK \+([\d\.,]+)s$/, '$1× 松木板 · $2× 钉子\nAFK +$3 秒'],
    [/^([\d\.,]+)× Pine Plank · ([\d\.,]+)× Small Mana Potion · ([\d\.,]+)× Accuracy Potion · ([\d\.,]+)× Defense Potion$/, '$1× 松木板 · $2× 小法力药水 · $3× 精准药水 · $4× 防御药水'],
    [/^([\d\.,]+)× Oak Logs · ([\d\.,]+)× Wire Coil\nBatch Craft up to ([\d\.,]+)$/, '$1× 橡木原木 · $2× 线圈\n批量制作达到 $3'],
    [/^([\d\.,]+)× Pine Logs · ([\d\.,]+)× Silk Coil\nBatch Craft up to ([\d\.,]+)$/, '$1× 松木原木 · $2× 丝圈\n批量制作达到 $3'],
    [/^([\d\.,]+)× Birch Logs, ([\d\.,]+)× Silk Coil$/, '$1× 桦木, $2× 丝圈'],
    [/^([\d\.,]+)× Cedar Logs, ([\d\.,]+)× Nylon Coil$/, '$1× 雪松木, $2× 尼龙圈'],
    [/^([\d\.,]+)× Cedar Logs · ([\d\.,]+)× Crypt Cord\nBatch Craft up to 25$/, '$1× 雪松木 · $2× 地穴绳\n最多批量制造25个'],
    [/^([\d\.,]+)× Maple Logs, ([\d\.,]+)× Crypt Cord$/, '$1× 枫木, $2× 地穴绳'],
    [/^([\d\.,]+)× Blacksteel Bar, ([\d\.,]+)× Wood Handle$/, '$1× 黑钢锭, $2× 木柄'],
    [/^([\d\.,]+)× Bronze Bar, ([\d\.,]+)× Wood Handle$/, '$1× 青铜锭, $2× 木柄'],
    [/^([\d\.,]+)× Iron Bar, ([\d\.,]+)× Wood Handle$/, '$1× 铁锭, $2× 木柄'],
    [/^([\d\.,]+)× Steel Bar, ([\d\.,]+)× Wood Handle$/, '$1× 钢锭, $2× 木柄'],
    [/^([\d\.,]+)× Glass Vial, ([\d\.,]+)× Birch Bark Resin$/, '$1× 玻璃小瓶, $2× 桦树皮树脂'],
    [/^([\d\.,]+)× Glass Vial, ([\d\.,]+)× Bat Teeth$/, '$1× 玻璃小瓶, $2× 蝙蝠牙齿'],
    [/^([\d\.,]+)× Glass Vial, ([\d\.,]+)× Redcap Fungus$/, '$1× 玻璃小瓶, $2× 红帽菌'],
    [/^([\d\.,]+)× Briar Oil, ([\d\.,]+)× Glass Vial$/, '$1× 石楠油, $2× 玻璃小瓶'],
    [/^([\d\.,]+)× Ghoul Eye, ([\d\.,]+)× Reinforced Vial$/, '$1× 食尸鬼的眼睛, $2× 加强小瓶'],
    [/^([\d\.,]+)× Cedar Bark Resin, ([\d\.,]+)× Reinforced Vial$/, '$1× 雪松皮树脂, $2× 加强小瓶'],
    [/^([\d\.,]+)× Bramble Heart, ([\d\.,]+)× Reinforced Vial$/, '$1× 荆棘之心, $2× 加强小瓶'],
    [/^([\d\.,]+)× Book, ([\d\.,]+)× Sea Essence$/, '$1× 书, $2× 海洋精华'],
    [/^([\d\.,]+)× Book, ([\d\.,]+)× Rock Essence$/, '$1× 书, $2× 岩石精华'],
    [/^([\d\.,]+)× Book, ([\d\.,]+)× Forest Essence$/, '$1× 书, $2× 森林精华'],
    [/^([\d\.,]+)× Reinforced Vial, ([\d\.,]+)× Spotted Mireheart$/, '$1× 加强小瓶, $2× 斑点矿心'],
    [/^([\d\.,]+)× Gold Ring, ([\d\.,]+)× Starstone$/, '$1× 金戒指, $2× 星彩石'],
    [/^([\d\.,]+)× Gold Ring, ([\d\.,]+)× Sapphire$/, '$1× 金戒指, $2× 蓝宝石'],
    [/^([\d\.,]+)× Gold Ring, ([\d\.,]+)× Ruby$/, '$1× 金戒指, $2× 红宝石'],
    [/^([\d\.,]+)× Gold Ring, ([\d\.,]+)× Emerald$/, '$1× 金戒指, $2× 翡翠'],
    [/^([\d\.,]+)× Gold Ring, ([\d\.,]+)× Diamond$/, '$1× 金戒指, $2× 钻石'],
    [/^([\d\.,]+)× Pine Plank · ([\d\.,]+)× Small Mana Potion · ([\d\.,]+)× Accuracy Potion · ([\d\.,]+)× Defense Potion\nBatch Alchemy up to ([\d\.,]+)$/, '$1× 松木板 · $2× 小法力药水 · $3× 精准药水 · $4× 防御药水\n批量炼金至 $5'],
    [/^([\d\.,]+)× Glass Glob$/, '$1× 玻璃小瓶'],
    [/^([\d\.,]+)× Steel Bar\nBatch Forge up to ([\d\.,]+)$/, '$1× 钢锭\n批量锻造至 $2'],
    [/^([\d\.,]+)× Iron Bar\nBatch Forge up to ([\d\.,]+)$/, '$1× 铁锭\n批量锻造至 $2'],
    [/^([\d\.,]+)× Bronze Bar\nBatch Forge up to ([\d\.,]+)$/, '$1× 青铜锭\n批量锻造至 $2'],
    [/^Batch Alchemy up to ([\d\.,]+)$/, '批量炼金至 $1'],
    [/^Batch Forge up to ([\d\.,]+)$/, '批量锻造至 $1'],
    [/^([\d\.,]+)× Copper Upgrade Bar$/, '$1× 铜升级锭'],
    [/^([\d\.,]+)× Upgrade Bar$/, '$1× 升级锭'],
    [/^([\d\.,]+)× Iron Bar$/, '$1× 铁锭'],
    [/^([\d\.,]+)× Bronze Bar$/, '$1× 青铜锭'],
    [/^([\d\.,]+)× Steel Bar$/, '$1× 钢锭'],
    [/^([\d\.,]+)× Blacksteel Bar$/, '$1× 黑钢锭'],
    [/^([\d\.,]+)× Enchanted Phial, ([\d\.,]+)× Anglerfish Oil$/, '$1× 附魔小瓶, $2× 琵琶鱼油'],
    [/^([\d\.,]+)× Silver Necklace, ([\d\.,]+)× Ruby$/, '$1× 银项链, $2× 红宝石'],
    [/^([\d\.,]+)× Silver Necklace, ([\d\.,]+)× Sapphire$/, '$1× 银项链, $2× 蓝宝石'],
    [/^([\d\.,]+)× Gold Necklace, ([\d\.,]+)× Diamond$/, '$1× 金项链, $2× 钻石'],
    [/^([\d\.,]+)× Gold Necklace, ([\d\.,]+)× Emerald$/, '$1× 金项链, $2× 翡翠'],
    [/^([\d\.,]+)× Gold Necklace, ([\d\.,]+)× Starstone$/, '$1× 金项链, $2× 星石'],
    [/^([\d\.,]+)× Runewood Logs, ([\d\.,]+)× Runed Coil$/, '$1× 符文木原木, $2× 符文线圈'],
    [/^([\d\.,]+)× Yew Logs, ([\d\.,]+)× Spectral Coil$/, '$1× 紫杉原木, $2× 光谱线圈'],
    [/^([\d\.,]+)× Elderwood Logs, ([\d\.,]+)× Abyssal Cord$/, '$1× 接骨木原木, $2× 深海绳'],
    [/^([\d\.,]+)× Arcane Phial, ([\d\.,]+)× Coastal Pearls$/, '$1× 奥术小瓶, $2× 海岸珍珠'],
    [/^([\d\.,]+)× Arcane Phial, ([\d\.,]+)× Willow Bark Resin$/, '$1× 奥术小瓶, $2× 柳树皮树脂'],
    [/^([\d\.,]+)× Arcane Phial$/, '$1× 奥术小瓶'],
    [/^([\d\.,]+)× Reinforced Vial$/, '$1× 加强小瓶'],
    [/^([\d\.,]+)× Small Water Spirit$/, '$1× 小水精灵'],
    [/^([\d\.,]+)× Small Ground Spirit$/, '$1× 小大地精灵'],
    [/^([\d\.,]+)× Small Fire Spirit$/, '$1× 小火焰精灵'],
    [/^([\d\.,]+)× Small Forest Spirit$/, '$1× 小森林精灵'],
    [/^([\d\.,]+)× Copper Bar$/, '$1× 铜锭'],
    [/^([\d\.,]+)× Copper Bar, ([\d\.,]+)× Wood Handle$/, '$1× 铜锭, $2× 木柄'],
    [/^([\d\.,]+)× Birch Plank · ([\d\.,]+)× Nails\nAFK \+([\d\.,]+)s$/, '$1× 桦木木板 · $2× 钉子\nAFK +$3秒'],
    [/^([\d\.,]+)× Oak Plank · ([\d\.,]+)× Small Mana Potion · ([\d\.,]+)× Accuracy Potion · ([\d\.,]+)× Defense Potion$/, '$1× 橡木板 · $2× 小法力药水 · $3× 精准药水 · $4× 防御药水'],
    [/^Iron Deposit \(Lv ([\d\.,]+)\)$/, '铁矿床 (等级  $1)'],
    [/^Bluewater Run \(Lv ([\d\.,]+)\)$/, '蓝水湾 (等级  $1)'],
    [/^Swamp Guardian \(Lv ([\d\.,]+)\)$/, '沼泽守护者 (等级  $1)'],
    [/^Coal Bed \(Lv ([\d\.,]+)\)$/, '煤层 (等级  $1)'],
    [/^Open Ocean \(Lv ([\d\.,]+)\)$/, '公海 (等级  $1)'],
    [/^River Bend \(Lv ([\d\.,]+)\)$/, '河湾 (等级  $1)'],
    [/^Runewood \(Lv ([\d\.,]+)\)$/, '符文木 (等级  $1)'],
    [/^Sand Vein \(Lv ([\d\.,]+)\)$/, '砂脉 (等级  $1)'],
    [/^Tin Seam \(Lv ([\d\.,]+)\)$/, '锡矿层 (等级  $1)'],
    [/^Abyssal Trench \(Lv ([\d\.,]+)\)$/, '深渊海沟 (等级  $1)'],
    [/^Bar \(Lv ([\d\.,]+)\)$/, '锭 (等级  $1)'],
    [/^Glass Glob \(Lv ([\d\.,]+)\) \— ([\d\.,]+)× Silica Sand$/, '玻璃球 (等级  $1) - $2× 硅砂'],
    [/^Bar \(Lv ([\d\.,]+)\) \— ([\d\.,]+)× Copper Ore$/, '锭 (等级  $1) - $2× 铜矿石'],
    [/^Bar \(Lv ([\d\.,]+)\) \— ([\d\.,]+)× Iron Ore$/, '锭 (等级  $1) - $2× 铁矿石'],
    [/^Bar \(Lv ([\d\.,]+)\) ([\d\.,]+)× Nightiron Ore$/, '锭 (等级  $1) $2× 夜铁矿石'],
    [/^Iron Bar \(Lv ([\d\.,]+)\) ([\d\.,]+)× Iron Ore$/, '铁锭 (等级  $1) $2× 铁矿石'],
    [/^Bar \(Lv ([\d\.,]+)\) ([\d\.,]+)× Asterium Ore \+ ([\d\.,]+)× Coal$/, '锭 (等级  $1) $2× 星宿矿石 + $3× 煤'],
    [/^Bar \(Lv ([\d\.,]+)\) ([\d\.,]+)× Nightiron Ore \+ ([\d\.,]+)× Coal$/, '锭 (等级  $1) $2× 夜铁矿石 + $3× 煤'],
    [/^Bar \(Lv ([\d\.,]+)\) ([\d\.,]+)× Iron Ore \+ ([\d\.,]+)× Coal$/, '锭 (等级  $1) $2× 铁矿石 + $3× 煤'],
    [/^Bar \(Lv ([\d\.,]+)\) \— ([\d\.,]+)× Copper Ore \+ ([\d\.,]+)× Tin Ore$/, '锭 (等级  $1) - $2× 铜矿石 + $3× 锡矿石'],
    [/^Bar \(Lv ([\d\.,]+)\) \— ([\d\.,]+)× Asterium Ore \+ ([\d\.,]+)× Coal$/, '锭 (等级  $1) - $2× 星宿矿石 + $3× 煤'],
    [/^Bar \(Lv ([\d\.,]+)\) \— ([\d\.,]+)× Nightiron Ore \+ ([\d\.,]+)× Coal$/, '锭 (等级  $1) - $2× 夜铁矿石 + $3× 煤'],
    [/^Bar \(Lv ([\d\.,]+)\) \— ([\d\.,]+)× Iron Ore \+ ([\d\.,]+)× Coal$/, '锭 (等级  $1) - $2× 铁矿石 + $3× 煤'],
    [/^Bar \(Lv ([\d\.,]+)\) \— ([\d\.,]+)× Draconyx Ore \+ ([\d\.,]+)× Coal$/, '锭 (等级  $1) - $2× 龙爪矿石 + $3× 煤'],
    [/^Deposit \(Lv ([\d\.,]+)\)$/, '矿床 (等级  $1)'],
    [/^Yew \(Lv ([\d\.,]+)\)$/, '紫杉 (等级  $1)'],
    [/^Toxic Frog \(Lv ([\d\.,]+)\)$/, '毒蛙 (等级  $1)'],
    [/^Swamp Spider \(Lv ([\d\.,]+)\)$/, '沼泽蜘蛛 (等级  $1)'],
    [/^Swamp Elemental \(Lv ([\d\.,]+)\)$/, '沼泽元素 (等级  $1)'],
    [/^Marsh Colossus \(Lv ([\d\.,]+)\)$/, '沼泽巨人 (等级  $1)'],
    [/^Gutter Rat \(Lv ([\d\.,]+)\)$/, '阴沟鼠 (等级  $1)'],
    [/^Bog Mite \(Lv ([\d\.,]+)\)$/, '沼泽螨 (等级  $1)'],
    [/^Bog Hydra \(Lv ([\d\.,]+)\)$/, '沼泽九头蛇 (等级  $1)'],
    [/^Bramble Sprite \(Lv ([\d\.,]+)\)$/, '荆棘精灵 (等级  $1)'],
    [/^Willow \(Lv ([\d\.,]+)\)$/, '柳木 (等级  $1)'],
    [/^River \(Lv ([\d\.,]+)\)$/, '河流 (等级  $1)'],
    [/^Nails \(x([\d\.,]+)\)$/, '钉子 (×$1)'],
    [/^ Table \(T([\d\.,]+)\)$/, '桌 (T$1)'],
    [/^Crafting Table \(T([\d\.,]+)\)$/, '制作桌 (T$1)'],
    [/^Birch Hut \(T([\d\.,]+)\)$/, '桦木小屋 (T$1)'],
    [/^Asterium Cluster \(Lv([\d\.,]+)\)$/, '星宿簇 (等级 $1)'],
    [/^Alchemy Table \(T([\d\.,]+)\)$/, '炼金台 (T$1)'],
    [/^Anvil \(T([\d\.,]+)\)$/, '铁砧 (T$1)'],
    [/^Bonfire \(T([\d\.,]+)\)$/, '篝火 (T$1)'],
    [/^Pine Hut \(T([\d\.,]+)\)$/, '松木小屋 (T$1)'],
    [/^Oak Hut \(T([\d\.,]+)\)$/, '橡木小屋 (T$1)'],
    [/^Campfire \(T([\d\.,]+)\)$/, '营火 (T$1)'],
    [/^Nightiron Vein \(Lv ([\d\.,]+)\)$/, '夜铁矿脉 (等级  $1)'],
    [/^Elderwood \(Lv ([\d\.,]+)\)$/, '接骨木 (等级  $1)'],
    [/^Sturgeon Depths \(Lv ([\d\.,]+)\)$/, '鲟鱼深海 (等级  $1)'],
    [/^Pine \(Lv ([\d\.,]+)\)$/, '松木 (等级  $1)'],
    [/^Marsh \(Lv ([\d\.,]+)\)$/, '沼泽 (等级  $1)'],
    [/^Coast \(Lv ([\d\.,]+)\)$/, '海岸 (等级  $1)'],
    [/^Cedar \(Lv ([\d\.,]+)\)$/, '雪松 (等级  $1)'],
    [/^Birch \(Lv ([\d\.,]+)\)$/, '桦树 (等级  $1)'],
    [/^Maple \(Lv ([\d\.,]+)\)$/, '枫树 (等级  $1)'],
    [/^HP ([\d\.,]+) · Atk ([\d\.,]+) · Def ([\d\.,]+) · Max ([\d\.,]+)$/, '生命值 $1 · 攻击 $2 · 防御 $3 · 最大 $4'],
    [/^Lv ([\d\.,]+) · Briar Oil ×([\d\.,]+), Glass Vial ×([\d\.,]+)$/, '等级 $1 · 石楠油 ×$2, 玻璃小瓶 ×$3'],
    [/^Lv ([\d\.,]+) · Cedar Bark Resin ×([\d\.,]+), Reinforced Vial ×([\d\.,]+)$/, '等级 $1 · 雪松皮树脂 ×$2, 加强小瓶 ×$3'],
    [/^Lv ([\d\.,]+) · Ghoul Eye ×([\d\.,]+), Reinforced Vial ×([\d\.,]+)$/, '等级 $1 · 食尸鬼的眼睛 ×$2, 加强小瓶 ×$3'],
    [/^Lv ([\d\.,]+) · Bramble Heart ×([\d\.,]+), Reinforced Vial ×([\d\.,]+)$/, '等级 $1 · 荆棘之心 ×$2, 加强小瓶 ×$3'],
    [/^Lv ([\d\.,]+) · Glass Vial ×([\d\.,]+), Bat Teeth ×([\d\.,]+)$/, '等级 $1 · 玻璃小瓶 ×$2, 蝙蝠牙齿 ×$3'],
    [/^Lv ([\d\.,]+) · Glass Vial ×([\d\.,]+), Birch Bark Resin ×([\d\.,]+)$/, '等级 $1 · 玻璃小瓶 ×$2, 桦树皮树脂 ×$3'],
    [/^Lv ([\d\.,]+)$/, '等级 $1'],
    [/^Unlocks at ([\d\.,]+) Favor$/, '解锁于 $1 徽章'],
    [/^Cast to inflict ([\d\.,]+) fire damage on enemy. Spending ([\d\.,]+) mana$/, '释放后对敌人造成 $1 火属性伤害。消耗 $2 法力'],
    [/^Needs ([\d\.,]+) Favor$/, '需要 $1 徽章'],
    [/^You need Defence ([\d\.,]+) to equip Steel Helm \(you are ([\d\.,]+)\).$/, '你需要达到防御 $1 才能装备 钢头盔 (你当前是 $2)'],
    [/^You need Defence ([\d\.,]+) to equip Steel Dagger \(you are ([\d\.,]+)\).$/, '你需要达到防御 $1 才能装备 钢匕首 (你当前是 $2)'],
    [/^You need Defence ([\d\.,]+) to equip Steel Sword \(you are ([\d\.,]+)\).$/, '你需要达到防御 $1 才能装备 钢剑 (你当前是 $2)'],
    [/^You need Defence ([\d\.,]+) to equip Steel Boots \(you are ([\d\.,]+)\).$/, '你需要达到防御 $1 才能装备 钢靴子 (你当前是 $2)'],
    [/^You need Defence ([\d\.,]+) to equip Steel Gloves \(you are ([\d\.,]+)\).$/, '你需要达到防御 $1 才能装备 钢手套 (你当前是 $2)'],
    [/^You need Defence ([\d\.,]+) to equip Steel Greaves \(you are ([\d\.,]+)\).$/, '你需要达到防御 $1 才能装备 钢护胫 (你当前是 $2)'],
    [/^You need Defence ([\d\.,]+) to equip Bronze Helm \(you are ([\d\.,]+)\).$/, '你需要达到防御 $1 才能装备 青铜头盔 (你当前是 $2)'],
    [/^You need Attack ([\d\.,]+) to equip Bronze Dagger \(you are ([\d\.,]+)\).$/, '你需要达到攻击 $1 才能装备 青铜匕首 (你当前是 $2)'],
    [/^You need Attack ([\d\.,]+) to equip Bronze Sword \(you are ([\d\.,]+)\).$/, '你需要达到攻击 $1 才能装备 青铜剑 (你当前是 $2)'],
    [/^You need Attack ([\d\.,]+) to equip Bronze Boots \(you are ([\d\.,]+)\).$/, '你需要达到攻击 $1 才能装备 青铜靴子 (你当前是 $2)'],
    [/^You need Attack ([\d\.,]+) to equip Bronze Gloves \(you are ([\d\.,]+)\).$/, '你需要达到攻击 $1 才能装备 青铜手套 (你当前是 $2)'],
    [/^You need Attack ([\d\.,]+) to equip Bronze Greaves \(you are ([\d\.,]+)\).$/, '你需要达到攻击 $1 才能装备 青铜护胫 (你当前是 $2)'],
    [/^You need Attack ([\d\.,]+) to equip Bronze Helm \(you are ([\d\.,]+)\).$/, '你需要达到攻击 $1 才能装备 青铜头盔 (你当前是 $2)'],
    [/^You need Attack ([\d\.,]+) to equip Steel Dagger \(you are ([\d\.,]+)\).$/, '你需要达到攻击 $1 才能装备 钢匕首 (你当前是 $2)'],
    [/^Requires Attack ([\d\.,]+)$/, '要求攻击 $1'],
    [/^Requires Defence ([\d\.,]+)$/, '要求防御 $1'],
    [/^Victory! XP \— Atk \+([\d\.,]+), Str \+([\d\.,]+), Def \+([\d\.,]+).$/, '胜利! 经验值 — 攻击 +$1, 力量 +$2, 防御 +$3.'],
    [/^Batch Craft up to ([\d\.,]+)$/, '批量制作升级到 $1'],
    [/^Requires L([\d\.,]+)$/, '需要 $1 级'],
    [/^Plot ([\d\.,]+)$/, '地块 $1'],
    [/^Level ([\d\.,]+)$/, '等级 $1'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^HP: ([\d\.,]+)$/, '生命值: $1'],
    [/^Atk: ([\d\.,]+)$/, '攻击: $1'],
    [/^Atk: ([\d\.,]+) · Str: ([\d\.,]+)$/, '攻击: $1 · 力量: $2'],
    [/^Atk: ([\d\.,]+) · Str: ([\d\.,]+) · Def: ([\d\.,]+)$/, '攻击: $1 · 力量: $2 · 防御: $3'],
    [/^Def: ([\d\.,]+)$/, '防御: $1'],
    [/^Restores: ([\d\.,]+) Mana$/, '回复: $1 法力'],
    [/^Attack: ([\d\.,]+) · Level: ([\d\.,]+)$/, '攻击: $1 · 等级: $2'],
    [/^Quality: ([\d\.,]+)\%$/, '质量: $1\%'],
    [/^Elderwood Logs \(×([\d\.,]+)\) \— yields ([\d\.,]+)$/, '接骨木 (x$1) - 生产 $2'],
    [/^Runewood Logs \(×([\d\.,]+)\) \— yields ([\d\.,]+)$/, '符文木 (x$1) - 生产 $2'],
    [/^Maple Logs \(×([\d\.,]+)\) \— yields ([\d\.,]+)$/, '枫木 (x$1) - 生产 $2'],
    [/^Birch Logs \(×([\d\.,]+)\) \— yields ([\d\.,]+)$/, '桦木 (x$1) - 生产 $2'],
    [/^Cedar Logs \(×([\d\.,]+)\) \— yields ([\d\.,]+)$/, '雪松木 (x$1) - 生产 $2'],
    [/^Pine Logs \(×([\d\.,]+)\) \— yields ([\d\.,]+)$/, '松木 (x$1) - 生产 $2'],
    [/^Willow Logs \(×([\d\.,]+)\) \— yields ([\d\.,]+)$/, '柳木 (x$1) - 生产 $2'],
    [/^Yew Logs \(×([\d\.,]+)\) \— yields ([\d\.,]+)$/, '紫杉木 (x$1) - 生产 $2'],
    [/^Oak Logs \(×([\d\.,]+)\) \— yields ([\d\.,]+)$/, '橡木 (x$1) - 生产 $2'],
    [/^\+([\d\.,]+)xp$/, '经验值 +$1'],
    [/^\+([\d\.,]+) Favor$/, '徽章 +$1'],
    [/^level ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^level: ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^XP (.+) \(need ([\d\.,]+) to Lv ([\d\.,]+)\)$/, '经验值 $1 (需要 $2 到 等级 $3)'],
    [/^Loot: (.+)g$/, '战利品：$1g'],
    [/^Value: (.+)g each$/, '价值：$1g 每个'],
    [/^Heals: (.+) HP$/, '治愈：$1 生命值'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);